"""Centralized environment configuration for nanoclaw."""

from __future__ import annotations

import os
from typing import Any

from dotenv import load_dotenv

load_dotenv()
load_dotenv(".env.local", override=True)


def env(name: str, default: str | None = None) -> str:
    value = os.getenv(name)
    if value is None:
        return "" if default is None else str(default)
    return str(value)


def env_str(name: str, default: str = "") -> str:
    return env(name, default).strip()


def env_bool(name: str, default: bool = False) -> bool:
    fallback = "true" if default else "false"
    return env_str(name, fallback).lower() in ("1", "true", "yes", "on")


def env_int(name: str, default: int) -> int:
    return int(env_str(name, str(default)))


def env_float(name: str, default: float) -> float:
    return float(env_str(name, str(default)))


RPC = env_str("RPC", "https://polygon-rpc.com")
RPC_URL = env_str("RPC_URL", RPC or "https://polygon-rpc.com")
WEB3_PROVIDER_URI = env_str("WEB3_PROVIDER_URI", RPC or "https://polygon-rpc.com")
RPC_FALLBACKS_RAW = env_str("RPC_FALLBACKS", "")
RPC_FALLBACKS = [x.strip() for x in RPC_FALLBACKS_RAW.split(",") if x.strip()]

WALLET = env_str("WALLET", "0x05eF62F48Cf339AA003F1a42E4CbD622FFa1FBe6")
PRIVATE_KEY = env_str("PRIVATE_KEY", "")
POLYGON_PRIVATE_KEY = env_str("POLYGON_PRIVATE_KEY", "")
RESOLVED_KEY = POLYGON_PRIVATE_KEY or PRIVATE_KEY

USDT = env_str("USDT", "0xc2132D05D31c914a87C6611C10748AEb04B58e8F")
USDC_ADDRESS = env_str("USDC", "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174")
USDC = USDC_ADDRESS
USDC_NATIVE_RAW = os.getenv("USDC_NATIVE")
USDC_NATIVE = (
    "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359"
    if USDC_NATIVE_RAW is None
    else str(USDC_NATIVE_RAW).strip()
)
WMATIC = env_str("WMATIC", "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270")
ROUTER = env_str("ROUTER", "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff")
QUICKSWAP_V2_ROUTER = env_str("QUICKSWAP_V2_ROUTER", "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff")
UNISWAP_V3_SWAP_ROUTER = env_str("UNISWAP_V3_SWAP_ROUTER", "0xE592427A0AEce92De3Edee1F18E0157C05861564")
UNISWAP_V3_QUOTER = env_str("UNISWAP_V3_QUOTER", "0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6")

LOG_PREFIX = env_str("LOG_PREFIX", "[nanoclaw]")
NO_COLOR = env_str("NO_COLOR", "")

COOLDOWN_MINUTES = env_int("COOLDOWN_MINUTES", 3)
PER_ASSET_COOLDOWN_MINUTES = env_int("PER_ASSET_COOLDOWN_MINUTES", 30)
PER_ASSET_COOLDOWN_SECONDS = PER_ASSET_COOLDOWN_MINUTES * 60
PER_WALLET_COOLDOWN = env_int("PER_WALLET_COOLDOWN", 180)
COPY_TRADING_ENABLED = env_bool("COPY_TRADING_ENABLED", True)

POL_USD_PRICE = env_float("POL_USD_PRICE", 0.10)
MIN_POL_FOR_GAS = env_float("MIN_POL_FOR_GAS", 0.005)
AUTO_TOPUP_POL = env_bool("AUTO_TOPUP_POL", True)
POL_TOPUP_AMOUNT = env_float("POL_TOPUP_AMOUNT", 0.03)
COPY_TRADE_PCT = env_float("COPY_TRADE_PCT", 0.28)
DEFAULT_MAX_COPY_RATIO = env_float("DEFAULT_MAX_COPY_RATIO", 0.20)
MAX_GWEI = env_float("MAX_GWEI", 80.0)
URGENT_GWEI = env_float("URGENT_GWEI", 120.0)
GAS_RPC_RETRY_ATTEMPTS = env_int("GAS_RPC_RETRY_ATTEMPTS", 2)

MIN_TRADE_USD = env_float("MIN_TRADE_USD", env_float("MIN_TRADE_USDC", 5.0))
FIXED_TRADE_USD_MIN = env_float("FIXED_TRADE_USD_MIN", MIN_TRADE_USD)
FIXED_TRADE_USD_MAX = env_float("FIXED_TRADE_USD_MAX", 10.0)
TRAILING_STOP_PCT = env_float("TRAILING_STOP_PCT", 5.0)
TAKE_PROFIT_PCT = env_float("TAKE_PROFIT_PCT", 5.0)
STRONG_SIGNAL_TP = env_float("STRONG_SIGNAL_TP", 12.0)
TAKE_PROFIT_SELL_PCT = env_float("TAKE_PROFIT_SELL_PCT", 0.45)
STRONG_TP_SELL_PCT = env_float("STRONG_TP_SELL_PCT", 0.60)

ENABLE_USDC_COPY = env_bool("ENABLE_USDC_COPY", False)
USDC_COPY_MIN_TRADE = env_float("USDC_COPY_MIN_TRADE", 5.0)
USDC_COPY_MAX_TRADE = env_float("USDC_COPY_MAX_TRADE", 15.0)

ENABLE_X_SIGNAL_EQUITY = env_bool("ENABLE_X_SIGNAL_EQUITY", False)
X_SIGNAL_EQUITY_MIN_STRENGTH = env_float("X_SIGNAL_EQUITY_MIN_STRENGTH", 0.60)
X_SIGNAL_MAX_EARNINGS_DAYS = env_float("X_SIGNAL_MAX_EARNINGS_DAYS", 5.0)
X_SIGNAL_FORCE_HIGH_CONVICTION = env_bool("X_SIGNAL_FORCE_HIGH_CONVICTION", True)
HIGH_CONVICTION_THRESHOLD = env_float("HIGH_CONVICTION_THRESHOLD", 0.82)
X_SIGNAL_FORCE_HIGH_CONVICTION_THRESHOLD = env_float(
    "X_SIGNAL_FORCE_HIGH_CONVICTION_THRESHOLD",
    HIGH_CONVICTION_THRESHOLD,
)
X_SIGNAL_STRONG_THRESHOLD = env_float("X_SIGNAL_STRONG_THRESHOLD", HIGH_CONVICTION_THRESHOLD)
X_SIGNAL_FORCE_ELIGIBLE_THRESHOLD = env_float(
    "X_SIGNAL_FORCE_ELIGIBLE_THRESHOLD",
    X_SIGNAL_FORCE_HIGH_CONVICTION_THRESHOLD,
)
X_SIGNAL_HIGH_CONVICTION_PREP_MIN_USDC = env_float("X_SIGNAL_HIGH_CONVICTION_PREP_MIN_USDC", 8.0)
X_SIGNAL_HIGH_CONVICTION_PREP_MIN_WMATIC = env_float("X_SIGNAL_HIGH_CONVICTION_PREP_MIN_WMATIC", 12.0)
FOLLOWED_EQUITIES_PATH = env_str("FOLLOWED_EQUITIES_PATH", "followed_equities.json")
X_SIGNAL_USDC_MIN = env_float(
    "X_SIGNAL_EQUITY_MIN_TRADE",
    env_float("X_SIGNAL_USDC_MIN", env_float("AUTO_USDC_FOR_X_SIGNAL_MIN_USDC", 5.0)),
)
X_SIGNAL_WMATIC_MIN_VALUE = env_float(
    "X_SIGNAL_WMATIC_MIN_VALUE",
    env_float("AUTO_USDC_FOR_X_SIGNAL_MIN_WMATIC_VALUE", 15.0),
)
AUTO_POPULATE_USDC_AMOUNT = env_float("AUTO_POPULATE_USDC_AMOUNT", 20.0)
AUTO_USDC_FOR_X_SIGNAL_MIN_USDC = env_float("AUTO_USDC_FOR_X_SIGNAL_MIN_USDC", X_SIGNAL_USDC_MIN)
AUTO_USDC_FOR_X_SIGNAL_MIN_WMATIC_VALUE = env_float(
    "AUTO_USDC_FOR_X_SIGNAL_MIN_WMATIC_VALUE",
    X_SIGNAL_WMATIC_MIN_VALUE,
)
X_SIGNAL_EQUITY_COOLDOWN_FIRST_SORT = env_bool("X_SIGNAL_EQUITY_COOLDOWN_FIRST_SORT", True)
X_SIGNAL_USDC_SAFE_FLOOR = env_float("X_SIGNAL_USDC_SAFE_FLOOR", 20.0)
X_SIGNAL_AUTO_USDC_TARGET = env_float("X_SIGNAL_AUTO_USDC_TARGET", 25.0)
X_SIGNAL_EQUITY_TRADE_PCT = env_float("X_SIGNAL_EQUITY_TRADE_PCT", 0.18)
X_SIGNAL_EQUITY_MAX_TRADE = env_float("X_SIGNAL_EQUITY_MAX_TRADE", 28.0)
X_SIGNAL_EQUITY_COOLDOWN_SECONDS = env_int(
    "X_SIGNAL_EQUITY_COOLDOWN_SECONDS",
    PER_ASSET_COOLDOWN_SECONDS,
)
X_SIGNAL_EQUITY_STRONG_TP_PCT = env_float("X_SIGNAL_EQUITY_STRONG_TP_PCT", 12.0)
X_SIGNAL_EQUITY_SELL_FRACTION = env_float("X_SIGNAL_EQUITY_SELL_FRACTION", 0.55)
CHAIN_HINT_WRONG_ETH_ADDRESSES = env_str("CHAIN_HINT_WRONG_ETH_ADDRESSES", "")
X_SIGNAL_DYNAMIC_TIER_HIGH_MIN = env_float("X_SIGNAL_DYNAMIC_TIER_HIGH_MIN", 0.90)
X_SIGNAL_DYNAMIC_USDC_GTE_TIER_HIGH = env_float("X_SIGNAL_DYNAMIC_USDC_GTE_TIER_HIGH", 20.0)
X_SIGNAL_DYNAMIC_USDC_GTE_FORCE_ELIGIBLE = env_float("X_SIGNAL_DYNAMIC_USDC_GTE_FORCE_ELIGIBLE", 15.0)
X_SIGNAL_DYNAMIC_USDC_BELOW_FORCE_ELIGIBLE = env_float("X_SIGNAL_DYNAMIC_USDC_BELOW_FORCE_ELIGIBLE", 12.0)

SWAP_SLIPPAGE_BPS = env_int("SWAP_SLIPPAGE_BPS", 100)
FALLBACK_ROUTER_SLIPPAGE_BPS_RAW = env_str("FALLBACK_ROUTER_SLIPPAGE_BPS", "")
FALLBACK_ROUTER_RETRY_SLIPPAGE_BPS_RAW = env_str("FALLBACK_ROUTER_RETRY_SLIPPAGE_BPS", "")
ONCHAIN_SWAP_RETRY_EXTRA_BPS = env_int("ONCHAIN_SWAP_RETRY_EXTRA_BPS", 50)
ONEINCH_SWAP_ENDPOINT = env_str("ONEINCH_SWAP_ENDPOINT", "https://api.1inch.dev/swap/v5.2/137/swap")
ONEINCH_SPENDER_ENDPOINT = env_str(
    "ONEINCH_SPENDER_ENDPOINT",
    "https://api.1inch.dev/swap/v5.2/137/approve/spender",
)
ONEINCH_API_KEY = env_str("ONEINCH_API_KEY", env_str("INCH_API_KEY", ""))
FALLBACK_ROUTER_SLIPPAGE_FLOOR_BPS = 600
HIGH_CONVICTION_FALLBACK_PRIMARY_BPS = env_int(
    "HIGH_CONVICTION_FALLBACK_PRIMARY_BPS",
    env_int("HIGH_CONVICTION_FALLBACK_SLIPPAGE_BPS", 4000),
)
HIGH_CONVICTION_FALLBACK_RETRY_BPS = env_int(
    "HIGH_CONVICTION_FALLBACK_RETRY_BPS",
    env_int("HIGH_CONVICTION_FALLBACK_RETRY_SLIPPAGE_BPS", 5000),
)

MAIN_STRATEGY_MIN_USDT_RESERVE = env_float("MAIN_STRATEGY_MIN_USDT_RESERVE", 25.0)
MAIN_STRATEGY_TP_TRIGGER_WMATIC_USD = env_float("MAIN_STRATEGY_TP_TRIGGER_WMATIC_USD", 52.0)
MAIN_STRATEGY_CUT_LOSS_WMATIC_USD = env_float("MAIN_STRATEGY_CUT_LOSS_WMATIC_USD", 40.0)
MAIN_STRATEGY_CUT_LOSS_MIN_WMATIC_BALANCE = env_float("MAIN_STRATEGY_CUT_LOSS_MIN_WMATIC_BALANCE", 50.0)
MAIN_STRATEGY_RESERVE_SELL_FRACTION = env_float("MAIN_STRATEGY_RESERVE_SELL_FRACTION", 0.45)
MAIN_STRATEGY_CUT_LOSS_SELL_FRACTION = env_float("MAIN_STRATEGY_CUT_LOSS_SELL_FRACTION", 0.28)
COPY_TRADE_AGGRESSIVE_THRESHOLD = env_float("COPY_TRADE_AGGRESSIVE_THRESHOLD", 0.20)

PROTECTION_MAX_DAILY_LOSS_PCT = env_int("PROTECTION_MAX_DAILY_LOSS_PCT", 15)
PROTECTION_MIN_POL_BALANCE = env_float("PROTECTION_MIN_POL_BALANCE", 2.0)
PROTECTION_MAX_TRADE_SIZE_USD = env_float("PROTECTION_MAX_TRADE_SIZE_USD", 35.0)
PROTECTION_GAS_MULTIPLIER = env_float("PROTECTION_GAS_MULTIPLIER", 1.25)
PROTECTION_FLUCTUATION_USDT_THRESHOLD = env_float("PROTECTION_FLUCTUATION_USDT_THRESHOLD", 30.0)
PROTECTION_FLUCTUATION_MIN_WMATIC = env_float("PROTECTION_FLUCTUATION_MIN_WMATIC", 50.0)
PROTECTION_FLUCTUATION_SELL_FRACTION = env_float("PROTECTION_FLUCTUATION_SELL_FRACTION", 0.25)
PROTECTION_FLUCTUATION_COOLDOWN_SECONDS = env_int("PROTECTION_FLUCTUATION_COOLDOWN_SECONDS", 1800)
PROTECTION_FLUCTUATION_MIN_SELL_USD = env_float("PROTECTION_FLUCTUATION_MIN_SELL_USD", 8.0)
PROTECTION_PROFIT_LOCK_PERCENT = env_float("PROTECTION_PROFIT_LOCK_PERCENT", 8.0)

NANOCLAW_AGENT_LAYER_ENABLED = env_bool("NANOCLAW_AGENT_LAYER_ENABLED", False)
NANOCLAW_TELEMETRY_TELEGRAM = env_bool("NANOCLAW_TELEMETRY_TELEGRAM", False)
NANOCLAW_AGENT_CAN_OVERRIDE_SWAP = env_bool("NANOCLAW_AGENT_CAN_OVERRIDE_SWAP", False)
NANOCLAW_AGENT_LAYER_ADVISORY = env_bool("NANOCLAW_AGENT_LAYER_ADVISORY", False)
NANOCLAW_GROK_ENABLED = env_bool("NANOCLAW_GROK_ENABLED", False)
GROK_API_KEY = env_str("GROK_API_KEY", env_str("XAI_API_KEY", ""))
GROK_API_BASE = env_str("GROK_API_BASE", "https://api.x.ai/v1")
GROK_MODEL = env_str("GROK_MODEL", "grok-2-latest")
TELEGRAM_BOT_TOKEN = env_str("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = env_str("TELEGRAM_CHAT_ID", "")
NANOCLAW_TRADE_ATTRIBUTION = env_bool("NANOCLAW_TRADE_ATTRIBUTION", True)

PORTFOLIO_BASELINE_USD_RAW = env_str("PORTFOLIO_BASELINE_USD", "")

GOOGLON = env_str("GOOGLON", "")
MSFTON = env_str("MSFTON", "")
APPLON = env_str("APPLON", "")
AMZNON = env_str("AMZNON", "")


def parse_float(raw: Any, default: float) -> float:
    try:
        return float(raw)
    except Exception:
        return float(default)


def get_resolved_key() -> str:
    return env_str("POLYGON_PRIVATE_KEY", "") or env_str("PRIVATE_KEY", "")
