"""
Environment-derived defaults for the swap bot entry (`clean_swap.py`).

Values are imported from the root `config.py` single source of truth.
"""

from __future__ import annotations

import config as cfg
from nanoclaw.config import X_SIGNAL

COOLDOWN_MINUTES = cfg.COOLDOWN_MINUTES
PER_ASSET_COOLDOWN_MINUTES = cfg.PER_ASSET_COOLDOWN_MINUTES
PER_ASSET_COOLDOWN_SECONDS = cfg.PER_ASSET_COOLDOWN_SECONDS
POL_USD_PRICE = cfg.POL_USD_PRICE
MIN_POL_FOR_GAS = cfg.MIN_POL_FOR_GAS
AUTO_TOPUP_POL = cfg.AUTO_TOPUP_POL
POL_TOPUP_AMOUNT = cfg.POL_TOPUP_AMOUNT
COPY_TRADE_PCT = cfg.COPY_TRADE_PCT
PER_WALLET_COOLDOWN = cfg.PER_WALLET_COOLDOWN
TRAILING_STOP_PCT = cfg.TRAILING_STOP_PCT
TAKE_PROFIT_PCT = cfg.TAKE_PROFIT_PCT
STRONG_SIGNAL_TP = cfg.STRONG_SIGNAL_TP
TAKE_PROFIT_SELL_PCT = cfg.TAKE_PROFIT_SELL_PCT
STRONG_TP_SELL_PCT = cfg.STRONG_TP_SELL_PCT
ENABLE_USDC_COPY = cfg.ENABLE_USDC_COPY
ENABLE_X_SIGNAL_EQUITY = cfg.ENABLE_X_SIGNAL_EQUITY
X_SIGNAL_EQUITY_MIN_STRENGTH = cfg.X_SIGNAL_EQUITY_MIN_STRENGTH
X_SIGNAL_MAX_EARNINGS_DAYS = cfg.X_SIGNAL_MAX_EARNINGS_DAYS
X_SIGNAL_FORCE_HIGH_CONVICTION = cfg.X_SIGNAL_FORCE_HIGH_CONVICTION
X_SIGNAL_FORCE_HIGH_CONVICTION_THRESHOLD = cfg.X_SIGNAL_FORCE_HIGH_CONVICTION_THRESHOLD
X_SIGNAL_STRONG_THRESHOLD = cfg.X_SIGNAL_STRONG_THRESHOLD
X_SIGNAL_FORCE_ELIGIBLE_THRESHOLD = cfg.X_SIGNAL_FORCE_ELIGIBLE_THRESHOLD
X_SIGNAL_HIGH_CONVICTION_PREP_MIN_USDC = cfg.X_SIGNAL_HIGH_CONVICTION_PREP_MIN_USDC
X_SIGNAL_HIGH_CONVICTION_PREP_MIN_WMATIC = cfg.X_SIGNAL_HIGH_CONVICTION_PREP_MIN_WMATIC
FOLLOWED_EQUITIES_PATH = cfg.FOLLOWED_EQUITIES_PATH
X_SIGNAL_USDC_MIN = cfg.X_SIGNAL_USDC_MIN
X_SIGNAL_WMATIC_MIN_VALUE = cfg.X_SIGNAL_WMATIC_MIN_VALUE
AUTO_POPULATE_USDC_AMOUNT = cfg.AUTO_POPULATE_USDC_AMOUNT
AUTO_USDC_FOR_X_SIGNAL_MIN_USDC = cfg.AUTO_USDC_FOR_X_SIGNAL_MIN_USDC
AUTO_USDC_FOR_X_SIGNAL_MIN_WMATIC_VALUE = cfg.AUTO_USDC_FOR_X_SIGNAL_MIN_WMATIC_VALUE
X_SIGNAL_EQUITY_COOLDOWN_FIRST_SORT = cfg.X_SIGNAL_EQUITY_COOLDOWN_FIRST_SORT
X_SIGNAL_USDC_SAFE_FLOOR = cfg.X_SIGNAL_USDC_SAFE_FLOOR
X_SIGNAL_AUTO_USDC_TARGET = cfg.X_SIGNAL_AUTO_USDC_TARGET

# Env for these keys is read only in nanoclaw.config.X_SIGNAL (single source of truth).
X_SIGNAL_DYNAMIC_TIER_HIGH_MIN = X_SIGNAL.TIER_HIGH_MIN
X_SIGNAL_DYNAMIC_USDC_GTE_TIER_HIGH = X_SIGNAL.USDC_GTE_TIER_HIGH
X_SIGNAL_DYNAMIC_USDC_GTE_FORCE_ELIGIBLE = X_SIGNAL.USDC_GTE_FORCE_ELIGIBLE
X_SIGNAL_DYNAMIC_USDC_BELOW_FORCE_ELIGIBLE = X_SIGNAL.USDC_BELOW_FORCE_ELIGIBLE
